import { domtify } from './core'
import './ext/addClass'
import './ext/each'
import './ext/map'
import './ext/filter'
import './ext/first'
import './ext/last'
import './ext/eq'
import './ext/get'
import './ext/append'
import './ext/extend'
import './ext/clone'
import './ext/add'
import './ext/prepend'
import './ext/after'
import './ext/before'
import './ext/replaceWith'
import './ext/next'
import './ext/prev'
import './ext/prevAll'
import './ext/prevUntil'
import './ext/is'

export default domtify
