import { domtify } from './core'
import './ext/addClass'
import './ext/each'
import './ext/map'
import './ext/filter'
import './ext/first'
import './ext/last'
import './ext/eq'
import './ext/get'
import './ext/append'
import './ext/extend'
import './ext/clone'
import './ext/add'
import './ext/is'
import './ext/prepend'
import './ext/after'
import './ext/before'
import './ext/replaceWith'
import './ext/css'
import './ext/next'
import './ext/nextAll'
import './ext/nextUntil'
import './ext/parents'
import './ext/parentsUntil'
// import './ext/prev'
// import './ext/prevAll'
// import './ext/prevUntil'


export default domtify
